sassoftware/quickstart-sas-viya-azure

sas-viya/azuredeploy.json

changed the descriptions for the 2 properties

(AZUREVIYA-102) Move VM sizes to Properties

---

sas-viya/README.md

 (AZUREVIYA-105) Add contact information to the read me

---

sas-viya/azuredeploy.parameters.json

- updated the location of the TravisCI temp data to new short term copy

(AZUREVIYA-100) Pull Request Review Issues

---

sas-viya/azuredeploy.json
sas-viya/azuredeploy.parameters.json

updates from latest pull request

Chlync azureviya 107

---

sas-viya/scripts/ansiblecontroller_prereqs.sh
sas-viya/scripts/nonansiblecontroller_prereqs.sh

- setup to autoskip one of the yum repos that is causing a lot of problems

(AZUREVIYA-117) RHEL 7.4 yum repolist was broken by Azure image update

---

sas-viya/playbooks/create_cas_sizing_file.yml

- most minimal change enables licences to default to a 4 core sku on an unlimited license.

(AZUREVIYA-115) Unlimited license support

---

sas-viya/azuredeploy.parameters.json
sas-viya/metadata.json

- updated azuredeploy.parameters.json to include an updated link and sas key for TravisCI's license
- updated the last updated date in metadata.json

(AZUREVIYA-128) Provide production external order to TravisCI

---

SUPPORT.md

Each GitHub repository in sassoftware must now have a SUPPORT.md file indicating
that bugs and feature requests should be opened as GitHub issues.

AZUREVIYA-130 Create a SUPPORT.md file in the GitHub repository

---

sas-viya/playbooks/roles/_setup_sas_orchestration_inventory_config/3.3/tasks/update.config.yml
sas-viya/playbooks/roles/predeploy_sas_orchestration_virk/defaults/main.yml
sas-viya/scripts/ansiblecontroller_prereqs.sh
sas-viya/scripts/ansiblecontroller_startup.sh

These are the changes necessary for azureviya 1.2

Azureviya 1.2

---

sas-viya/azuredeploy.parameters.json
sas-viya/metadata.json
sas-viya/playbooks/post.deployment.yml

- Updated azuredeploy.parameters.json to new license link with short timeframe
- updated metadata.json with todays date to reflect the last update timestamp

(AZUREVIYA-135) Pull request prep

---

sas-viya/azuredeploy.json
sas-viya/scripts/ansiblecontroller_prereqs.sh

- implemented temporary workaround suggested by azure. Unlikely this will be escolated to production, but gives a valid deployment target in the mean time.

(AZUREVIYA-148) azure-cli installation through yum stopped working

---

sas-viya/README.md

Add as  recommended best practice to include on one deployment per resource group.  Also, in the resource groups that contain deployments, include only the deployment in the resource group to facilitate deletion as a unit.

(AZUREVIYA-172) One deployment per resource group

---

sas-viya/azuredeploy.json

(AZUREVIYA-180) AnsiblePhase2 is now removed with merge to common code

---

sas-viya/azuredeploy.json

Edited azuredeploy.json file deploymentmirror description to reflect no gzip.

(AZUREVIYA-179) Fix deploymentmirror desc-no gzip

---

sas-viya/ansible/playbooks/post_deployment.yml
sas-viya/file_tree.txt
sas-viya/scripts/runners/install_runner.sh

- typo referred to common code rather than azure custom code for restart service

(AZUREVIYA-182) Services not restarting properly

---

sas-viya/README.md

Corrected broken TOC links.  Corrected an additional incorrect file path.  Incorporated general edits from running publications Content Analyzer tool.

(AZUREVIYA-172) (AZUREVIYA-177) Path corrections.

---

sas-viya/scripts/ansiblecontroller_prereqs.sh

- updated git clone to be done in a loop with a wait

(AZUREVIYA-185) git clone hardening

---

README.md
sas-viya/README.md

Update the link to point the repository root.

(AZUREVIYA-175) Add contributor agreement to repository

---

sas-viya/scripts/ansiblecontroller_prereqs.sh

- jq install change was unnecessary. Removing.

(AZUREVIYA-187) install_runner log file indicates failure for jq

---

README.md

Update the README title to SAS Viya on the Azure Cloud

(AZUREVIYA-189) update the README title

---

sas-viya/azuredeploy.parameters.json
sas-viya/metadata.json

- updated ephemeral license information
- updated metadata.json with latest release date

(AZUREVIYA-155) Pull request prep

---

sas-viya/azuredeploy.json
sas-viya/file_tree.txt

Brian Moore recommended this after the latest pull request failure.

(AZUREVIYA-191) Changing _artifactsLocationSasToken to a secure string

---

sas-viya/README.md
sas-viya/azuredeploy.json

Update information for hover text for new fields: CAS Node Count and CAS Worker VM SKU

(AZUREVIYA-206) Hover text info for new fields

---

sas-viya/scripts/ansiblecontroller_prereqs.sh
sas-viya/scripts/nonansiblecontroller_prereqs.sh

- Updated to latest common code
- merged in changes from hotfix 1.3.2
- disable selinux since viya-ark no longer does

(AZUREVIYA-225) Support for Viya 3.5

---

sas-viya/README.md

Updated troubleshooting step to indicate that primary deployment name when deployment is run via UI template is "Microsoft.Template".

(AZUREVIYA-109) Microsoft.Template -UI deployment

---

sas-viya/README.md

Updated document links and versions.

(AZUREVIYA-229) Focused Documentation - Viya 3.5 upgrade

---

sas-viya/README.md
sas-viya/azuredeploy.json
sas-viya/azuredeploy.parameters.json
sas-viya/metadata.json
sas-viya/nestedtemplates/createNetworkSubtemplate.json

- updated with latest upstream azure changes

(AZUREVIYA-230) Merge upstream azure changes

---

sas-viya/README.md

Corrected software versions in SOE and link to Data Agent doc.

(AZUREVIYA-229) Viya 3.5 upgrade

---

sas-viya/metadata.json

- Updated the metadata.json to use the latest date

(AZUREVIYA-210) Pull Request Prep

---

sas-viya/azuredeploy.json
sas-viya/metadata.json

- Pull request hit issues with concat in the style guide
- metadata.json date format needs changed

(AZUREVIYA-210) Pull Request fixes

---

sas-viya/README.md
sas-viya/metadata.json

Update software version numbers in metadata.json file.

(AZUREVIYA-241) Update descrition in metadata.json

---

sas-viya/ansible/roles/prepare_deployment/deployment_mirror/tasks/main.yml

- added rsync to explicit yum installs

(AZUREVIYA-250) Mirror deploys are breaking on mirror download

---

sas-viya/README.md

Added additional Appendix containing information/policies about tracking.

(AZUREVIYA-271) Focused Documentation - Add Guid

---

sas-viya/azuredeploy.json

Creating pull request since Microsoft says this works on their side. Added a guid deployment.

Azureviya 261

---

sas-viya/ansible/roles/prepare_deployment/deployment_mirror/tasks/main.yml

- updated package icu to be libicu

(AZUREVIYA-273) Mirror deployments are not working

---

sas-viya/README.md
sas-viya/azuredeploy.json
sas-viya/nestedtemplates/createNetworkSubtemplate.json
sas-viya/nestedtemplates/run_ansible_script.json

- updated item where schema version was reverted to old version
- updated readme link format to azure format

(AZUREVIYA-279) Pull Request Prep
